server:
  port: 8095

zuul:
  routes:
    notification-service:
      path: /notification/**
      stripPrefix: false
      serviceId: notification-service
      sensitiveHeasders:
    assign-service:
      path: /assign/**
      stripPrefix: false
      serviceId: assign-service
      sensitiveHeasders:
    push-service:
      path: /push/**
      stripPrefix: false
      serviceId: push-service
      sensitiveHeasders:
    media-service:
      path: /media/**
      stripPrefix: false
      serviceId: media-service
      sensitiveHeasders:
    user-service:
      path: /user/**
      stripPrefix: false
      serviceId: user-service
      sensitiveHeasders:
    scheduler-service:
      path: /scheduler/**
      stripPrefix: false
      serviceId: scheduler-service
      sensitiveHeasders:

security:
  oauth2:
    client:
      clientId: zuulService
      clientSecret: zuulServiceSecret
      authorized-grant-types: authorization_code,refresh_token,password
      scope: openid
    resource.jwt:
      key-pair:
        alias: zuulServiceKey
        store-password: zuulServicePassword

---

spring:
  profiles: docker
