server:
  port: 8095

zuul:
  routes:
    notification-service:
      path: /notification/**
      stripPrefix: false
      serviceId: notification-service
      sensitiveHeasders:
    assign-service:
      path: /assign/**
      stripPrefix: false
      serviceId: assign-service
      sensitiveHeasders:
    push-service:
      path: /push/**
      stripPrefix: false
      serviceId: push-service
      sensitiveHeasders:
    media-service:
      path: /media/**
      stripPrefix: false
      serviceId: media-service
      sensitiveHeasders:
    user-service:
      path: /user/**
      stripPrefix: false
      serviceId: user-service
      sensitiveHeasders:
    scheduler-service:
      path: /scheduler/**
      stripPrefix: false
      serviceId: scheduler-service
      sensitiveHeasders:

---

spring:
  profiles: docker
